// Simulasi database kelulusan dalam bentuk array
const dataKelulusan = [
{nim:'K1401241036', nama:'Ardhyasiwi Pradnya Sakti', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'F2401241018', nama:'Belimbing Salima Kamal', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241011', nama:'Saskia Aulia Mayeri', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'C2401241040', nama:'Gilbert Alvaro Iglecio Bintang', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H1401241084', nama:'Ghina Melanie Taufik', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241009', nama:'Hadisti Najmi Alkhonsa', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H3401241014', nama:'Jo Ann Katrin', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241126', nama:'Muhamad Hadi Timanta Kaban ', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'A4401241026', nama:'Muhamad  Alif Rahman', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241245', nama:'Muhammad Andika Laksono', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H3401241021', nama:'Muhammad Sandy Fatriawansyah', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241176', nama:'Muhammad Sulthan Arkan Mustafa', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H1401241076', nama:'Mellisa Ayu Prawtaningrum', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H2401241129', nama:'Shabrina Al Alauna Kiandra', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241022 ', nama:'Nur Maharani Al Karim ', status:'Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241217', nama:'Desy Boban', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241026', nama:'Athira Gibran', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H3401241065', nama:'Nailasari Nurhasanah', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'G8401241106', nama:'Aurora Zulaikha Aqilah', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H1401241005', nama:'Faisal Ahmad Rifai', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241051', nama:'Meisya Salsabila', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H2401241118', nama:'Yogy Nakawa Ginting', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H2401241017', nama:'Qanita Marsya Putri Kurniawan', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'M0404241058', nama:'Sekar Laras Ayuning Karti', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'A2401241131', nama:'Ahmad Kahfi', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241132', nama:'Muhamad Arian Saputra', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H3401241120', nama:' Anantha Putra Dewanto', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241119', nama:'Rafi Helmy Ramadhan ', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H2401241149', nama:'Agha Ghaisan Aqil', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'K1401241182', nama:'Muhammad Sayyid Habibullah', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H2401241035', nama:'Alyssa Augustya Putri', status:'Tidak Lolos', pilihan:'Departemen Ekonomi Kreatif'},
{nim:'H2401241048', nama:'Alya Syiffa Maharani', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I2401241017', nama:'Bilqist Azalia Shaqila', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'F3401241126', nama:'Chatya Putri Dwinata', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I3401241013', nama:' Sabri Al-falah', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'H2401241019', nama:'Dina Chairatul Hasni', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'H3401241139', nama:'Dini Rahma Putriani', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'E2401241057', nama:'Khairunnisa Naia Safira', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I2401241097', nama:'Fawwaz Raihan Aziz', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I3401241133', nama:'Hafizh Nasywa Krisnawala', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I3401241007', nama:'M. Rafi Furqon', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'A4401241045', nama:'Mahira Delia Arbanty', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I340124123', nama:'Muhammad Nauval Rezky Dwiananda', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'L1401241009', nama:'Muhammad Reza Rahman', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'E3401241123', nama:'Tesalonika Lisnawanti Purba', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'H2401241133', nama:'Zafar Khan Abasi ', status:'Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I3401241146', nama:'Aulia Fatiha', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I1401241085', nama:'Elsa Sulistianingsih', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'A1401241082', nama:'Fathur Zaki Rayyan Dhani', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'H4401241104', nama:'Fitria Robiatul Adawiah', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'H4401241081', nama:'Zaidan Nazhifa Ridwan', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'E3401241112', nama:'Hikmatun Khasanah ', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'H3401241140', nama:'Fauzan Hanif Mufty', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'D3401241092', nama:'Muhammad Faiz Hanif', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'B0401241176', nama:'Muhammad Firdaus Nuzula', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'H5401241004', nama:'Nasywan Maulana Althaf', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'H4401241017', nama:'Reisita Dhea Gustiyana', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'F3401241049', nama:'Samudra Ghifary Galistan', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I3401241058', nama:'Vika Julianida', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'C2401241002', nama:'Septiana Dewi', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I2401241101', nama:'Henry Vincent Miracle Keraf', status:'Tidak Lolos', pilihan:'Biro Kolaborasi dan Kemitraan'},
{nim:'I3401241052', nama:'Anggie Aulya', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'H1401241073', nama:'Virena Harin', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'F2401241021', nama:'Khadeeja Zuhayra Raisa Shazfa Falisha', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'I3401241138', nama:'Atiqa Salsabila', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'C2401241001', nama:'Diana Ervina Putri', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'M0403241067', nama:'Mirabel Nasywa Rajendraputri', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'G4401241004', nama:'Dwi Cindy Hapsari', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'F3401241053', nama:'Intan Zabrina', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'H1401241007', nama:'Nauval Mahfudz Muhtadi', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'M0403241023', nama:'Dzaky Abyan', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'I3401241003', nama:'Pirgiawan Restu Ardani', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'E140241116', nama:'Lingga Naufal Azura', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'A2401241040', nama:'Reihan Athallah Akbar', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'H2401241010', nama:'Nasrullah Ibrahim', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'H1401241098', nama:'Drajat Fadhlan Rahman', status:'Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'G3401241089', nama:'Bima Yoga Satrio', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'D1401241126', nama:'Ratu Dewi Fitriya Fazrin', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'F3401241024', nama:'Atika Zahra', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'C3401241019', nama:'Melia Sekar Hindiati', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'F4401241005', nama:'Aulia Putra Narino ', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'H2401241099', nama:'Raditya Syahputra Armand S.', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'D1401241114', nama:'Ardiena Tsaufvira Daud Mahesa Putri', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'I1401241084', nama:'Fadila Putri Susanti ', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'H2401241123', nama:'Fatimah Azzahra Wicaksono', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'G3401241039', nama:'Zaina Rahma Salsabila Siregar ', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'F2401241077', nama:'Amira Ahnaf', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'M0403241141', nama:'Rendi Ramadana', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'M0401241100', nama:'Muhammad Alvaro Satria Priyambada', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'H5401241083', nama:'Aura Mustika Fana ', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'K1401241089', nama:'Muhammad Salman Romadhon', status:'Tidak Lolos', pilihan:'Departemen Pengembangan Sumber Daya Mahasiswa'},
{nim:'M0401241055', nama:'Qanita Basimah Kurnia', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241029', nama:'Aurelia Fury', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241011', nama:'Shabrina Nur Izzati', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241006', nama:'Fadly Syabani Ardiansyah', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'F2401241006', nama:'Febriananta Rafa Fadilah', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241016', nama:'Najwa Salsabila M.N', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241058', nama:'Muhammad Khayruhanif', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241084', nama:'Cahya Raras Mitayani', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241104', nama:'Fitria Angelita Delvi', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'G3401241074', nama:'Ashila Air Widiarta', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0403241038', nama:'Muhammad Haidar', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241079', nama:'Azka Raditya Hafidz', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241002', nama:'Adi Pratama', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0403241050', nama:'Ayubi Fathan', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'F3401241100', nama:'Mauliddio Lazuardi Wahyudin', status:'Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241005', nama:'Andhias Abdillah Ridho', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241071', nama:'Darell Belva', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'G8401241008', nama:'Cantika Mutiara Asmarandana', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'F2401241071', nama:'Rasheed Al Kahfi Setiawan', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241099', nama:'Kholishotur Rofi\'ah', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'A2401241134', nama:'Muhamad Nabil', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'C5401241073', nama:'Ghalib Wiragana Nugroho', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241015', nama:'Nisrina Salsabila', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241044', nama:'Panji Elang Permanajati', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'G8401241065', nama:'Zahra Maulida Sihaloho', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'E2401241027', nama:'Adinda Agnia', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'G2401241056', nama:'Kayla Salsabila', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'M0401241105', nama:'Putra Ramadhana', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'K1401241223', nama:'M Ibrahim Arsyad', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'F2401241075', nama:'Nur Haya Hanifah', status:'Tidak Lolos', pilihan:'Biro Riset Pengembangan'},
{nim:'F3401241128', nama:'Adli Rafiansyah Amin ', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'H5401241019', nama:'Aisyah Jazlyn Rizqia	', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'H4401241087', nama:'Alifah Aqela Edra', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'A2401241162', nama:'Amanda Nabilatusyifa', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'E3401241022', nama:'Andika Satria Putra', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'A2401241095', nama:'Ayu Kesuma Ningtyas ', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'G8401241093', nama:'Denia Catherine Cecilia Gultom', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'I1401241021', nama:'Gusti Karebet Damar Panuluh', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'E3401241013', nama:'Ishlauddini Putri', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'G3401241046', nama:'Novallin Fajri', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'H3401241124', nama:'Pasha Halabi Ikhsanal Haq', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'C4401241001', nama:'Reno Ivanardra', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'C2401241080 ', nama:'Ribka Mandauly Y. P.', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'E2401241079', nama:'Rivandi Zidane', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'K1401241005', nama:'Thaha Abdurrahman', status:'Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'A4401241079', nama:'Ahmad Farid Pradana K', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'G3401241112', nama:'Aisyah Salsabillah Putri', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'I3401241038', nama:'Aqila Ramadhani Sandji Idrus', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'E1401241108', nama:'Bramatio Muhammad Putera', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'H4401241108', nama:'Gita Sastradipraja', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'A2401241168', nama:'Hawa Zahra Ramadhani', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'I2401241012', nama:'Ikhwan Ranthisi Harisman ', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'H3401241142', nama:'Laura Amalia G.', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'I2401241006', nama:'Muhamad Kamal', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'E1401241013', nama:'Natasya Az Zahra', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'A3401241005', nama:'Safira Aulia Anandita', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'I2401241043', nama:'Sarah Anjani ', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'E1401241055', nama:'Silvia Humaira', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'M0401241129', nama:'Yasmin Aufaahani Abdullah', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'A4401241023', nama:'Zalfa Zahira', status:'Tidak Lolos', pilihan:'Departemen Sosial Lingkungan Hidup'},
{nim:'G3401241052', nama:'Ahmad Faizullah Kianafa Rizwan', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'G4401241048', nama:'Alya Azkia Jauza', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'K1401241175', nama:'Aulia Zahra Anindita', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'M0404241027', nama:'Aurelia Zefanya Silalahi', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'C5401241037', nama:'Bayu Dwi Aprianto', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'K1401241139', nama:'Chelsea Anastacia Dealova', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'F2401241086', nama:'Chelsea Cheryla', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'F1401241086', nama:'Deva Anisa Nurohmah', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'F3401241096', nama:'Faizah Aura Salsabila', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'C4401241010', nama:'Fathur Syamsy Dhuha', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'M0405241004', nama:'Fatimah Nur Abdillah', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'H2401241121', nama:'Jovan Ali Muzakki', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'H2401241042', nama:'Nadia Sabila', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'M0403241124', nama:'Naura Girlastin Bachri', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'H3401241074', nama:'Reina Amani Wahyudi', status:'Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'I3401241077', nama:'Dini Mulya Sahida', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'I2401241016', nama:'Devina Aura Cantika', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'A2401241085', nama:'Elsya Kara Saviour Latumeten', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'C3401241018', nama:'Evan Prayoga', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'D2401241022', nama:'Geri Fasha', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'H5401241082', nama:'Ila Rahmawiani', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'M0403241031', nama:'Muh. Abdillah Muhklis', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'H3401241017', nama:'Muhammmad Nabil Febriansyah', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'C3401241008', nama:'Nanda Amanda', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'H1401241021', nama:'Rachmadiyani Chelsea', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'C3401241012', nama:'Rafi Arundaya', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'A2401241121', nama:'Rhemael Hizkia Simanjuntak', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'K1401241123', nama:'Syifa Fauziah', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'M0401241022', nama:'Uma Keisha Abriana', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'F4401241045', nama:'Vieira Gabriela Rumapea', status:'Tidak Lolos', pilihan:'Departemen Seni dan Budaya'},
{nim:'F3401241095', nama:'Hudzaifah Abdurrahman', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'G4401241037', nama:'George Valentynus Pasaribu', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'H4401241024', nama:'Nhimas Ayu Kinanthi', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'I3401241040', nama:'Akmal Maulana Al Sulfi', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'B1401241004', nama:'Reynaldi Christian', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'E3401241019', nama:'Mirza Pratama ', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'H2401241012', nama:'Ririn Dwi Kumalasari', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'H4401241099', nama:'Auliya Syifa\'a Muthmainnah', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'H3401241043', nama:'Jhonson Prasetio', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'I3401241020', nama:'Dafina Azzahra Sinambela', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'I2401241107', nama:'Alyssa Fidelia Akbar', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'F4401241041', nama:'Vena Herdiana Damayanti', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'I3401241016', nama:'Gundara w.s', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'M0404241018', nama:'Nadia Anggita Hardianzah', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'H4401241001', nama:'Yogi Syahputra', status:'Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'G3401241040', nama:'Dyaz Miftah Hidayat', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'I2401241029', nama:'Inaayah Zahra Solehati ', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'G7401241036', nama:'Juan Dani Immanuel Sitorus', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'H3401241040', nama:'Valencia Sastra Wijaya ', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'A4401241005', nama:'Jihan Adzhani Maulana', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'C1401241120', nama:'Aprilliana Ayesha Parsa ', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'A3401241013', nama:'Nadhira Ilfa Syakira ', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'G3401241043', nama:'Azzahra \'Azizatunnada', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'K1401241110', nama:'Den Leo Pramudya ', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'E2401241052', nama:'Gilang Ramadhan', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'A2401241019', nama:'Fadillah Rizkyani Sitorus', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'H3401241046', nama:'Attalya Yizrel Mamushe S', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'M0402241042', nama:'Hernawati', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'G8401241026', nama:'Nabila Alisaputri Anori', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'G8401241011', nama:'Amelia Rizani', status:'Tidak Lolos', pilihan:'Departemen Advokasi Kesejahteraan Mahasiswa'},
{nim:'C4401241079', nama:'Adel Muhammad Azka', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'D1401241047', nama:'Arifin Muhammad Amin ', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'H3401241115', nama:'Attala Ortzi Fahlefi', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'F2401241127', nama:'Ayesha Nashwa Raida Sulthoni', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'C1401241093', nama:'Dida Liandaru Zahro', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'K1401241230', nama:'Farhan Dzaky Siregar', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'F2401241008', nama:'Juan Andrew', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'F3401241040', nama:'Muhammad Azkiya Arrayyan ', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'F3401241044', nama:'Muhammad Rahmat Dafa', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'F1401241060', nama:'Rafif Syafiq Mahardika', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'D1401241007', nama:'Salwa Nasyahta Adzira', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'E1401241031', nama:'Faza Muthiurrohman', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'A2401241022', nama:'Sketsa Smaradhana Bumi', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'I3401241153', nama:'Tanaya Fathiatul Makiah Hartono', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'C5401241808', nama:'Tristan Alano Putra Wisnu', status:'Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'F4401241017', nama:'Chayara Elya Azhar', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'C2401241105', nama:'Cherina Qibtiyah Ashzahrah', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'A1401241005', nama:' Robbani Alfaiz', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'A2401241178', nama:'Dhandi Rafa Satvika Hartanto ', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'E2401241007', nama:'Diskha Azqyaraya Maulida', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'H5401241010', nama:'Savina Rahma Alia', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'A2401241160', nama:'Hafiz Ikhtiari Ramadhan', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'E4401241042', nama:'Kevin Azriansyah', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'C3401241032', nama:'Muhamad Fahrurijal Akbar ', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'F4401241043', nama:'Muhammad Iqbal Falih Harahap', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'A1401241070', nama:'Muhammad Iqbal Firdaus ', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'A0401241029', nama:'Muhammad Khairan Syazani', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'G7401241025', nama:'Muhammad Rendy Atala Qolsaputra', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'F3401241058', nama:'NAUFAL AULIYA', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'A0401241033', nama:'Zacky Mubarok', status:'Tidak Lolos', pilihan:'Departemen Pemuda Olahraga'},
{nim:'I2401241002', nama:'Aginda Malika Danish Naira', status:'Lolos', pilihan:'Biro Internal'},
{nim:'H3401241003', nama:'Andhika Arya Ramdhani', status:'Lolos', pilihan:'Biro Internal'},
{nim:'M0402241081', nama:' Naufal Fadhlurahman', status:'Lolos', pilihan:'Biro Internal'},
{nim:'I2401241055', nama:'Devira Yosi Yatsika', status:'Lolos', pilihan:'Biro Internal'},
{nim:'I3401241005', nama:'Dimaz Maulana Arby', status:'Lolos', pilihan:'Biro Internal'},
{nim:'F2401241034', nama:'Fauziyyah Az Zahrah', status:'Lolos', pilihan:'Biro Internal'},
{nim:'A3401241053', nama:'Hilal Putranta', status:'Lolos', pilihan:'Biro Internal'},
{nim:'H1401241095', nama:'Imelda Triyani', status:'Lolos', pilihan:'Biro Internal'},
{nim:'M0403241033', nama:'Micko Fahraezi', status:'Lolos', pilihan:'Biro Internal'},
{nim:'H2401241046', nama:'Muhamad Rizky Fadillah', status:'Lolos', pilihan:'Biro Internal'},
{nim:'I3401241002', nama:'Muhammad Fernanda Athallah Ar-Rafii', status:'Lolos', pilihan:'Biro Internal'},
{nim:'F4401241064', nama:'Muhammad Raihan Ridho Ramadhan', status:'Lolos', pilihan:'Biro Internal'},
{nim:'M0403241013', nama:'Muhammad Wafi Robbani', status:'Lolos', pilihan:'Biro Internal'},
{nim:'G2401241078', nama:'Rafael Moza Christopher', status:'Lolos', pilihan:'Biro Internal'},
{nim:'I3401241100', nama:'Davina Reizka Dara', status:'Lolos', pilihan:'Biro Internal'},
{nim:'C5401241038', nama:'Adhitya Fauzi Ibarni', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'C5401241025', nama:'Anugrah Gede Wuryanti', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'I2401241049', nama:'Arishanty Khair Nugroho', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'I3401241028', nama:'Aryo Nugroho', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'H2401241130', nama:'Asiah Ummu Alifa', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'F2401241047', nama:'Bintang Haura Fauziah', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'H1401241100', nama:'Damarrois Hammami', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'A3401241112', nama:'Khalilah Syawa Setyoputri', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'K1401241113', nama:'Muhammad Wahid Julian', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'A2401241091', nama:'Muhammad Yusuf Azzam', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'I2401241105', nama:'Nazwa Sakinah Harun', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'K1401241861', nama:'Qothru Shofiatalhidayah', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'C2401241041', nama:'Refky Rifaldi', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'C4401241059', nama:'Siti Aliffah', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'G3401241014', nama:'Wira Tirta Mahardika', status:'Tidak Lolos', pilihan:'Biro Internal'},
{nim:'M0404241019', nama:'Adelia Aisha Akhlaqul Karimah', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'H5401241088', nama:'Arib Nurfayyadh', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'M0403241037', nama:' Nasywan Islamy', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'G7401241007', nama:'Syifa Khairunissa', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'M0401241060', nama:'M. Haikal Tabrani', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'M0401241061', nama:'Annisa Marwah S', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'H2401241050', nama:'M. Alfath Al Johari', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'F2401241023', nama:'Izati Minhalina Riyanisa', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'H5401241028', nama:'Hanania Isyqiya Mulyana', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'M0403241010', nama:'Safira Ayu Damayanti', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'C2401241081', nama:'Fattah Ahmadi Nejad', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'F2401241048', nama:'Jennifer Chelsea Okto Susanto', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'G4401241049', nama:'Zahra Dini Khiesa', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'I1401241016', nama:'Rike Nur Syafitri ', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'A3401241030', nama:'Ergoputra Kusuma Sanjaya', status:'Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'D2401241033', nama:'Zahra Apriani', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'H4401241011', nama:'Shakira Marwa Luption Putri', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'G3401241025', nama:'Nandita Putri Farahiya', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'H1401241040', nama:'Aliya Karina Naela', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'M0403241121', nama:'Nabil Musannif Siregar', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'C5401241057', nama:'Bayu Mulia Pratama', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'F4401241092', nama:'Annisa Rahmah', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'E4401241088', nama:'Adi Maulana', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'I1401241029', nama:'Kamil Muhamad Febrian', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'M0405241085', nama:'Fildzah Wahyu Izzati ', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'I1401241030', nama:'Amelia Rahma Tanlala', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'M0403241120', nama:'Muhammad Naufal Dzaki Jatmika', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'H2401241053', nama:'Muhamad Fahri Nurnazib ', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'M0401241085', nama:'Muhammad  Fadhilah Athif', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'H1401241039', nama:'Nadhira Putri Yovantya', status:'Tidak Lolos', pilihan:'Departemen Akademik Prestasi'},
{nim:'C5401241040', nama:'Lutfi Meilano Risuseno', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'M0401241057', nama:'Thoriq Ar-ridfi', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'M0404241020', nama:'Aufa Dzuljalali Wal Ikram', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'F2401241091', nama:'Airra Dzikria Rizatara', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'G0401241031', nama:'Fannikha Haeny Dzikriany', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'H1401241071', nama:'M. Rizky Saifi Yusuf', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'H4401241109', nama:'M. Rizky Pratama', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'A4401241081', nama:'Nadira Naura Nurrachman', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'I3401241152', nama:'Beryl Zorafael Rudi', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'H2401241112', nama:'Andika Ahmad Nugraha ', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'C5401241004', nama:'Miftahul Jannah', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'D3401241074', nama:'Asyam Syaddad Farras ', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'D2401241121', nama:'Edelweiss', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'H5401241125', nama:'Aqeela Malihah Husna', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'M0403241053', nama:'Fawwaz  Alvino', status:'Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'G3401241020', nama:'Latifah Nastiti Mansur', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'G3401241088 ', nama:'Gitalis Hayati Nufus ', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'I3402241121', nama:'Muthia Shabrina', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'H4401241032', nama:'Hilwa Hamidah', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'E3401241095', nama:'Aprilia Intan Fanimala', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'D3401241019 ', nama:'Dina Meisyah Putri', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'H1401241014', nama:'Revina Putri Herdiana', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'H4401241077', nama:'Abdul Muhit', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'I3401241116', nama:'Annisa Hani Ikhtiar', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'C4401241011', nama:'Muhammad Taufik', status:'Tidak Lolos', pilihan:'Departemen Dinamika Gerakan Politik'},
{nim:'F3401241067', nama:'Fachry Rizqi Amada', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'A1401241048', nama:'Farhan Ibrahim Budiarto', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'C4401241016', nama:'Noval Abdurrahman ', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'K1401241066', nama:'Salman Maliki', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'G7401241037', nama:'Muhammad Akmal Harahap', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'G3401241036', nama:'Najwa Nurfa\'izah Rhamadhanti', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'C1401241054', nama:'Balqis Humaira', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'F1401241108', nama:'Farrell Malik Al Fazial', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'H1401241043', nama:'Sekarayu Rasyha Ftari Azzalia', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'M0403241136', nama:'Sangkara Arya', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'D1401241088', nama:'Riqqa Aulya Maharani ', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'E4401241113', nama:'Rizky Arkananta Firmana Gunawan ', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'D1401241004', nama:'Rizki Hazmi Putra', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'D3401241024', nama:'Asya Bianca Jasmine', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'M0401241023', nama:'Nailah Afia Tsabita', status:'Lolos', pilihan:'Biro Media dan Branding'},
{nim:'F1401241073', nama:'Yuniar Ramadhania Hakim', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'M0403241022', nama:'Faisal Mumtaz Hidayat', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'E1401241043', nama:'Rafi Fajar Rengganu', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'E3401241145', nama:'Rajendra Fikri Ramadhan', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'A2401241009', nama:'Rachmalia Putri', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'I3401241070', nama:'Altafaris Wibisono', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'K1401241118', nama:'Muhammad Zidane Aulia', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'M0401241014', nama:'Maulana Firdaus', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'M0403241133', nama:'Aufa Rafli Sofwan Pasya ', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'K1401241082', nama:'Ananda Rahmania Ramadhani', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'H5401241106', nama:'Naufal Yazid Al Ghoziy', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'I3401241048', nama:'Rivani Rahmadewi ', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'F2401241064', nama:'Margarita Utari ', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'A3401241052', nama:'Jasmine Malyda Amara', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'},
{nim:'E3401241087', nama:'Ahmad Hariz Faza', status:'Tidak Lolos', pilihan:'Biro Media dan Branding'}
];

// Fungsi untuk mengecek kelulusan
function cekKelulusan() {
    const inputData = document.getElementById("inputData").value.trim();
    const errorElement = document.getElementById("error");

    // Reset pesan error sebelumnya
    errorElement.textContent = "";

    if (inputData === "") {
        errorElement.textContent = "Harap masukkan Nomor Pendaftaran atau Nama!";
        return;
    }

    // Cari data dalam "database" dengan case-insensitive
    const hasil = dataKelulusan.find(data => 
        data.nim === inputData || 
        data.nama.toLowerCase() === inputData.toLowerCase()
    );

    if (hasil) {
        try {
            // Simpan hasil ke localStorage dengan key yang unik
            localStorage.setItem("hasilKelulusan", JSON.stringify(hasil));
            
            // Redirect ke halaman hasil
            window.location.href = "hasil.html";
        } catch (e) {
            errorElement.textContent = "Gagal menyimpan data ke localStorage. Coba lagi!";
            console.error("localStorage error:", e);
        }
    } else {
        // Tampilkan error jika data tidak ditemukan
        errorElement.textContent = "Data tidak ditemukan. Periksa kembali input Anda!";
    }
}
